//
// Generated by spiderweak using Python.
//

#ifndef CPP_PARAMETERS_H
#define CPP_PARAMETERS_H

#define HUNIT 1

#endif //CPP_PARAMETERS_H

const int hunit = HUNIT;

const float lstm_cell_input_weights[4 * HUNIT] = {-0.47074094414711, 0.5782343149185181, 0.7150036096572876, 0.8580639362335205};

const float lstm_cell_hidden_weights[4 * HUNIT * HUNIT] = {0.31322693824768066, -0.032405853271484375, -0.9226136207580566, 0.2227618396282196};

const float lstm_cell_bias[4 * HUNIT] = {0.3858514428138733, 1.0, 0.3026246428489685, 0.3853971064090729};

float lstm_cell_hidden_layer[HUNIT] = {0.3922583758831024};
float lstm_cell_cell_states[HUNIT] = {0.6355526447296143};

const float dense_weights[HUNIT] = {0.7915790677070618};
const float dense_bias = 0.25034016370773315;
