//
// Generated by spiderweak using Python.
//

#ifndef CPP_PARAMETERS_H
#define CPP_PARAMETERS_H

#define HUNIT 1

#endif //CPP_PARAMETERS_H

const int hunit = HUNIT;

const float lstm_cell_input_weights[4 * HUNIT] = {0.6187129020690918, 0.3575434684753418, 0.24292391538619995, -0.27248668670654297};

const float lstm_cell_hidden_weights[4 * HUNIT * HUNIT] = {-0.11512160301208496, 0.3561599850654602, 0.7860531210899353, 0.4919528365135193};

const float lstm_cell_bias[4 * HUNIT] = {0.13711969554424286, 1.0, 0.2720763683319092, 0.19261819124221802};

float lstm_cell_hidden_layer[HUNIT] = {0.561694860458374};
float lstm_cell_cell_states[HUNIT] = {1.996629238128662};

const float dense_weights[HUNIT] = {1.6718257665634155};
const float dense_bias = 0.26913774013519287;
