//
// Generated by spiderweak using Python.
//

#ifndef CPP_PARAMETERS_H
#define CPP_PARAMETERS_H

#define HUNIT 1

#endif //CPP_PARAMETERS_H

const int hunit = HUNIT;

const float lstm_cell_input_weights[4 * HUNIT] = {-0.5231911540031433, 0.8216911554336548, 0.2396586686372757, -0.54414963722229};

const float lstm_cell_hidden_weights[4 * HUNIT * HUNIT] = {-0.12456011772155762, -0.08975572139024734, 0.7595713138580322, 0.6320444345474243};

const float lstm_cell_bias[4 * HUNIT] = {-0.03327455371618271, 1.0, -0.2779948115348816, -0.03327660635113716};

float lstm_cell_hidden_layer[HUNIT] = {-0.25512707233428955};
float lstm_cell_cell_states[HUNIT] = {-0.7792224287986755};

const float dense_weights[HUNIT] = {-1.1823006868362427};
const float dense_bias = 0.2913602292537689;
