//
// Generated by spiderweak using Python.
//

#ifndef CPP_PARAMETERS_H
#define CPP_PARAMETERS_H

#define HUNIT 1

#endif //CPP_PARAMETERS_H

const int hunit = HUNIT;

const float lstm_cell_input_weights[4 * HUNIT] = {1.324167013168335, -0.013807296752929688, 0.6922830939292908, 1.5952683687210083};

const float lstm_cell_hidden_weights[4 * HUNIT * HUNIT] = {-0.9575628042221069, 0.05279545113444328, 0.21890102326869965, -0.17991240322589874};

const float lstm_cell_bias[4 * HUNIT] = {0.1780415177345276, 1.0, -0.36609962582588196, 0.08077209442853928};

float lstm_cell_hidden_layer[HUNIT] = {-0.16726075112819672};
float lstm_cell_cell_states[HUNIT] = {-0.24871277809143066};

const float dense_weights[HUNIT] = {-1.4370193481445312};
const float dense_bias = 0.40733733773231506;
